// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNVOXTybmLj4Ko6RC185R_lQt-MXnP4VY',
    appId: '1:823806478257:web:35b90ff457ce63b6365f90',
    messagingSenderId: '823806478257',
    projectId: 'maintenancemobileapp-99f7c',
    authDomain: 'maintenancemobileapp-99f7c.firebaseapp.com',
    storageBucket: 'maintenancemobileapp-99f7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN_dwXeMkYxK7B8DfnryWf1AEDg_crPj4',
    appId: '1:823806478257:android:722343f19264ac3f365f90',
    messagingSenderId: '823806478257',
    projectId: 'maintenancemobileapp-99f7c',
    storageBucket: 'maintenancemobileapp-99f7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_uF2L6RZn9kO3KhD8-mxtfuNOT8REW6Q',
    appId: '1:823806478257:ios:ae5d491147e03bfc365f90',
    messagingSenderId: '823806478257',
    projectId: 'maintenancemobileapp-99f7c',
    storageBucket: 'maintenancemobileapp-99f7c.firebasestorage.app',
    iosBundleId: 'com.example.brikolikMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_uF2L6RZn9kO3KhD8-mxtfuNOT8REW6Q',
    appId: '1:823806478257:ios:ae5d491147e03bfc365f90',
    messagingSenderId: '823806478257',
    projectId: 'maintenancemobileapp-99f7c',
    storageBucket: 'maintenancemobileapp-99f7c.firebasestorage.app',
    iosBundleId: 'com.example.brikolikMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNVOXTybmLj4Ko6RC185R_lQt-MXnP4VY',
    appId: '1:823806478257:web:70075ecd2287beeb365f90',
    messagingSenderId: '823806478257',
    projectId: 'maintenancemobileapp-99f7c',
    authDomain: 'maintenancemobileapp-99f7c.firebaseapp.com',
    storageBucket: 'maintenancemobileapp-99f7c.firebasestorage.app',
  );

}